import { it, expect } from 'vitest';
import { THEMES, type ChestRarity } from '../src/meta/catalog';
import { initialMeta, parseMeta } from '../src/meta/store';
import { openChest, rollSkin, CHEST_ODDS } from '../src/meta/chests';

it('has six unique skins and only the starter unlocked',()=>{expect(THEMES).toHaveLength(6);expect(new Set(THEMES.map(t=>t.id)).size).toBe(6);expect(initialMeta().unlockedThemes).toEqual(['lotus']);});
it('every chest has the exact configured rarity distribution and higher rare odds',()=>{
 for(const chest of ['common','rare','legendary']as const){const counts={common:0,rare:0,legendary:0};for(let i=0;i<1000;i++){let calls=0;const skin=rollSkin(chest,()=>calls++===0?(i+.5)/1000:.2);counts[skin.rarity]++;}expect(counts).toEqual(Object.fromEntries(Object.entries(CHEST_ODDS[chest]).map(([k,v])=>[k,v*10])));}
 expect(CHEST_ODDS.common.rare).toBeLessThan(CHEST_ODDS.rare.rare);expect(CHEST_ODDS.rare.rare).toBeLessThan(CHEST_ODDS.legendary.rare);
});
it('skins inside each rarity have equal chance and include the starter',()=>{for(const rarity of ['common','rare','legendary']as ChestRarity[]){const pool=THEMES.filter(t=>t.rarity===rarity);const firstRoll=rarity==='common'?.1:rarity==='rare'?.8:.99;for(let i=0;i<pool.length;i++){let calls=0;expect(rollSkin('common',()=>calls++===0?firstRoll:(i+.5)/pool.length).id).toBe(pool[i].id);}}});
it('insufficient balance or unknown collection cannot spend or roll',()=>{const meta=initialMeta();let calls=0;const rng=()=>{calls++;return .1;};expect(openChest(meta,'glasshouse',rng)).toBeNull();expect(openChest(meta,'fake',rng)).toBeNull();expect(calls).toBe(0);});
it('new reward costs exactly 100 and persists ownership without auto-equipping',()=>{const meta=initialMeta();meta.collectionBalances.glasshouse=140;const r=openChest(meta,'glasshouse',()=>.4)!;expect(r.theme.id).toBe('sand');expect(r.duplicate).toBe(false);expect(r.state.collectionBalances.glasshouse).toBe(40);expect(r.state.unlockedThemes).toEqual(['lotus','sand']);expect(r.state.selectedTheme).toBe('lotus');expect(r.state.completedCollections).toEqual(['glasshouse']);expect(meta.collectionBalances.glasshouse).toBe(140);});
it('duplicate refunds exactly 25 to the source collection only',()=>{const meta=initialMeta();meta.collectionBalances={glasshouse:7,lighthouse:100,townhouse:12};const r=openChest(meta,'lighthouse',()=>0)!;expect(r.theme.id).toBe('lotus');expect(r.duplicate).toBe(true);expect(r.refund).toBe(25);expect(r.state.collectionBalances).toEqual({glasshouse:7,lighthouse:25,townhouse:12});expect(r.state.unlockedThemes).toEqual(['lotus']);});
it('repeat openings preserve surplus and cannot overspend',()=>{let meta=initialMeta();meta.collectionBalances.glasshouse=250;meta=openChest(meta,'glasshouse',()=>.4)!.state;expect(meta.collectionBalances.glasshouse).toBe(150);meta=openChest(meta,'glasshouse',()=>.4)!.state;expect(meta.collectionBalances.glasshouse).toBe(75);expect(meta.completedCollections).toEqual(['glasshouse']);expect(openChest(meta,'glasshouse',()=>.4)).toBeNull();});
it('a fully owned catalog still yields duplicates without rerolling',()=>{const meta=initialMeta();meta.unlockedThemes=THEMES.map(t=>t.id);meta.collectionBalances.townhouse=100;const r=openChest(meta,'townhouse',()=>.99)!;expect(r.duplicate).toBe(true);expect(r.theme.id).toBe('aurora');expect(r.state.collectionBalances.townhouse).toBe(25);});
it('migrates old demo unlocks to starter while retaining all earned parts',()=>{const meta=parseMeta({version:2,selectedTheme:'dusk',unlockedThemes:['lotus','dusk','sand'],collectionBalances:{glasshouse:115,lighthouse:50,townhouse:5}});expect(meta.unlockedThemes).toEqual(['lotus']);expect(meta.selectedTheme).toBe('lotus');expect(meta.collectionBalances).toEqual({glasshouse:115,lighthouse:50,townhouse:5});});
it('v3 roundtrip preserves earned skins, selected theme and permanently opened pictures',()=>{const meta=initialMeta();meta.collectionBalances.townhouse=100;const opened=openChest(meta,'townhouse',()=>.99)!.state;opened.selectedTheme='aurora';expect(parseMeta(JSON.parse(JSON.stringify(opened)))).toEqual(opened);});
