import { it, expect } from 'vitest';
import { initialMeta, parseMeta } from '../src/meta/store';
import { rewardPlacement, rollCollection, collectionProgress } from '../src/meta/economy';
import { newGame, place, emptyBoard } from '../src/core/game';
import { shapeById } from '../src/core/shapes';

it('all collection wallets start empty',()=>{expect(initialMeta().collectionBalances).toEqual({glasshouse:0,lighthouse:0,townhouse:0});});
it('weight boundaries are exactly 50/40/10',()=>{expect([0,.499999,.5,.899999,.9,.999999].map(n=>rollCollection(()=>n))).toEqual(['glasshouse','glasshouse','lighthouse','lighthouse','townhouse','townhouse']);const counts={glasshouse:0,lighthouse:0,townhouse:0};for(let i=0;i<1000;i++)counts[rollCollection(()=>(i+.5)/1000) as keyof typeof counts]++;expect(counts).toEqual({glasshouse:500,lighthouse:400,townhouse:100});});
it('one cleared line gives one piece at combo one; score remains independent',()=>{const meta=initialMeta(),move=place(newGame(),0,6,2)!;const reward=rewardPlacement(meta,move,()=>.6);expect(reward.total).toBe(1);expect(reward.state.collectionBalances).toEqual({glasshouse:0,lighthouse:1,townhouse:0});expect(move.state.score).toBe(110);expect(meta.collectionBalances.lighthouse).toBe(0);});
it('a move with no line gives no currency and makes no random draw',()=>{let calls=0;const meta=initialMeta(),reward=rewardPlacement(meta,place(newGame(),0,0,0)!,()=>{calls++;return .1;});expect(reward.state).toBe(meta);expect(reward.awards).toEqual([]);expect(reward.total).toBe(0);expect(calls).toBe(0);});
it('simultaneous row and column each roll once, both get the current combo',()=>{const s=newGame();s.board=emptyBoard();for(let i=0;i<8;i++){s.board[3][i]=1;s.board[i][4]=1;}s.board[3][4]=0;s.hand=[{shape:shapeById('single-0'),color:1},null,null];s.combo=2;s.hasCombo=true;const move=place(s,0,4,3)!;const rolls=[.1,.95];let calls=0;const reward=rewardPlacement(initialMeta(),move,()=>rolls[calls++]);expect(move.multiplier).toBe(3);expect(reward.total).toBe(6);expect(calls).toBe(2);expect(reward.state.collectionBalances).toEqual({glasshouse:3,lighthouse:0,townhouse:3});});
it('100 completes the picture and overflow is preserved without changing the fixed probabilities',()=>{const meta=initialMeta();meta.collectionBalances.glasshouse=99;const s=newGame();s.combo=3;s.hasCombo=true;const reward=rewardPlacement(meta,place(s,0,6,2)!,()=>.1);expect(reward.state.collectionBalances.glasshouse).toBe(103);expect(collectionProgress(reward.state,'glasshouse')).toBe(100);expect(reward.total).toBe(4);});
it('reward multiplier follows the actual combo reset',()=>{const s=newGame();s.combo=1;s.hasCombo=false;s.misses=3;const reward=rewardPlacement(initialMeta(),place(s,0,6,2)!,()=>.95);expect(reward.total).toBe(1);expect(reward.state.collectionBalances.townhouse).toBe(1);});
it('validates saved currency and preserves valid balances and themes',()=>{const meta=parseMeta({version:3,selectedTheme:'dusk',unlockedThemes:['dusk','fake'],collectionBalances:{glasshouse:111,lighthouse:-1,townhouse:2.5}});expect(meta.collectionBalances).toEqual({glasshouse:111,lighthouse:0,townhouse:0});expect(meta.selectedTheme).toBe('dusk');expect(meta.unlockedThemes).toEqual(['lotus','dusk']);expect(parseMeta({version:3,collectionBalances:{glasshouse:Infinity,lighthouse:'20'}}).collectionBalances.glasshouse).toBe(0);});
it('migrates earlier theme selection and prototype parts once without fake progress',()=>{const meta=parseMeta({version:1,selectedTheme:'sand',unlockedThemes:['lotus','sand'],collectionParts:{glasshouse:[],lighthouse:[0,1,1,100],townhouse:[]}});expect(meta.selectedTheme).toBe('lotus');expect(meta.unlockedThemes).toEqual(['lotus']);expect(meta.collectionBalances).toEqual({glasshouse:0,lighthouse:2,townhouse:0});expect(meta.version).toBe(3);});
it('unknown or malformed save resets safely',()=>{expect(parseMeta(null)).toEqual(initialMeta());expect(parseMeta({version:300})).toEqual(initialMeta());});
